#### Numpy 

Numoy is a fundamental library for scientific computing in Python. It provides support for array, matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy, focusing on arrays, and vectorized operations.

In [1]:
!pip install numpy

In [5]:
import numpy as np

## creating arrays using numpy [1d arrya]

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # shape of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # i row & 5 columns 

array([[1, 2, 3, 4, 5]])

In [10]:
arr2 = np.array([[1,2,3,4,5,6,7]])
arr2.shape

(1, 7)

In [15]:
# 2D array 
arr2 = np.array([[1,2,3,4,5,6,7], [8,7,80,90,40,50,70]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  7 80 90 40 50 70]]
(2, 7)


In [16]:
# creating arrays with some built in function 
#arnage() :- It creates an array of evenly spaced numbers over a given range.
# numpy.arange(start, stop, step)

np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [17]:
# we can rehsape 
np.arange(0,10,2).reshape(5,1) # 5 row and 1 columns


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
# ones() : ones() NumPy me ek function hai jo sirf ek kaam karta hai:
# given shape ka array banata hai, jisme saare elements = 1 hote hain

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# eye():idenntity matrix , diagonal elements are 1 and rest all zero 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# Attributes of numpy

arr = np.array([[1,2,3,4,5,6,7], [8,7,80,90,40,50,70]])

print("Array:\n ", arr)
print("shape", arr.shape)
print("Size (no of elements)", arr.size)
print("Datatype: ", arr.dtype)
print("Item size (in bytes ): ", arr.itemsize)

Array:
  [[ 1  2  3  4  5  6  7]
 [ 8  7 80 90 40 50 70]]
shape (2, 7)
Size (no of elements) 14
Datatype:  int64
Item size (in bytes ):  8


In [30]:
## Numpy vectorized operation

arr1= np.array([1,2,3,4,5])
arr2 =np.array([10,20,30,4,5])

# Element wise addtion
print("addition: ", arr1+ arr2)


# Element wise substraction and same for divison and multiplication
print("substraction: ", arr1- arr2)

addition:  [11 22 33  8 10]
substraction:  [ -9 -18 -27   0   0]


In [34]:
## Universal function that basicaly apply on entire array

arr = np.array([1,2,3,45,55])

# square root 
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log 
print(np.log(arr))

[1.         1.41421356 1.73205081 6.70820393 7.41619849]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 3.49342711e+19
 7.69478527e+23]
[ 0.84147098  0.90929743  0.14112001  0.85090352 -0.99975517]
[0.         0.69314718 1.09861229 3.80666249 4.00733319]


In [45]:
# array slicing and indexing 

arr = np.array([[1,2,34],[74,85,96],[41,52,52]])
print("Arrays\n ",arr)

Arrays
  [[ 1  2 34]
 [74 85 96]
 [41 52 52]]


In [49]:
arr[0][0]

np.int64(1)

In [58]:
arr[1:,2:]


array([[96],
       [52]])

In [62]:
print(arr[0][0])
print(arr[0:2])

1
[[ 1  2 34]
 [74 85 96]]


In [67]:
## modify array elements 
arr[0,0 ]= 100000
print(arr)

[[100000      2     34]
 [   100    100    100]
 [   100    100    100]]


In [68]:
arr[1:] =100
print(arr)

[[100000      2     34]
 [   100    100    100]
 [   100    100    100]]


In [70]:
## stastical concept ---Normalization
# to have a mean of 0 and stardard deviation of 1
data = np.array([1,2,3,4,5])

# calculate the mean and standard deviaton 
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data 
normalized_data= (data -mean)/ std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [75]:
# to calculate mean, median, mode

data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean 
mean = np.mean(data)
print("Mean of the data:- ", mean)

#median
median = np.median(data)
print("Median of the data:- ", median)

# std deviation 
std_dev = np.std(data)
print("standard deviation:- ", std_dev)

# varaince 
variance = np.var(data)
print("varaincce of data:- ", variance)

Mean of the data:-  5.5
Median of the data:-  5.5
standard deviation:-  2.8722813232690143
varaincce of data:-  8.25


In [ ]:
# logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)

# if i want to get value
data[data>5]

[False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])